import { useState } from "react";
import type { FormEvent, ReactNode } from "react";
import { Building2 } from "lucide-react";
import { Link, Navigate, useNavigate, useSearchParams } from "react-router-dom";
import { useAuth } from "../../hooks/useAuth";
import { companyDestination } from "../../utils/companyRouting";

function Shell({ title, subtitle, children }: { title: string; subtitle: string; children: ReactNode }) {
  return <main className="flex min-h-screen items-center justify-center bg-slate-50 px-4 py-10"><section className="w-full max-w-md rounded-3xl border border-slate-200 bg-white p-7 shadow-xl sm:p-9">
    <div className="flex items-center gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-slate-950 text-white"><Building2 size={22}/></span><span className="text-xl font-bold text-slate-950">LedgerFlow</span></div>
    <h1 className="mt-8 text-2xl font-semibold text-slate-950">{title}</h1><p className="mt-2 text-sm leading-6 text-slate-500">{subtitle}</p>{children}
  </section></main>;
}
const inputClass = "mt-2 w-full rounded-xl border border-slate-200 px-3.5 py-3 text-sm outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100";
const buttonClass = "mt-6 w-full rounded-xl bg-slate-950 px-5 py-3 text-sm font-semibold text-white disabled:cursor-not-allowed disabled:opacity-50";

export function LoginPage() {
  const auth = useAuth(); const navigate = useNavigate();
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  if (auth.user) return <Navigate to={`/${companyDestination(auth.companies, auth.preferences) === "setup" ? "company-setup" : companyDestination(auth.companies, auth.preferences) === "select" ? "select-company" : "dashboard"}`} replace/>;
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setError(null); try { await auth.login(email.trim(), password); navigate("/", { replace: true }); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to sign in."); setBusy(false); } }
  return <Shell title="Welcome back" subtitle="Sign in to open your company ledger."><form onSubmit={submit} className="mt-6"><label className="text-sm font-medium">Email<input type="email" required autoComplete="email" value={email} onChange={(e)=>setEmail(e.target.value)} className={inputClass}/></label><label className="mt-4 block text-sm font-medium">Password<input type="password" required autoComplete="current-password" value={password} onChange={(e)=>setPassword(e.target.value)} className={inputClass}/></label>{(error??auth.error)&&<p role="alert" className="mt-4 text-sm text-rose-700">{error??auth.error}</p>}<button disabled={busy} className={buttonClass}>{busy?"Signing in...":"Sign in"}</button></form><div className="mt-5 flex justify-between text-sm"><Link to="/forgot-password" className="text-blue-700">Forgot password?</Link><Link to="/register" className="font-medium text-blue-700">Create account</Link></div></Shell>;
}

export function RegisterPage() {
  const auth=useAuth(); const navigate=useNavigate(); const [name,setName]=useState(""); const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [confirmPassword,setConfirmPassword]=useState(""); const [error,setError]=useState<string|null>(null); const [busy,setBusy]=useState(false);
  async function submit(event:FormEvent){event.preventDefault();if(password!==confirmPassword){setError("Passwords do not match.");return}setBusy(true);setError(null);try{await auth.register(name.trim(),email.trim(),password);navigate("/company-setup",{replace:true});}catch(cause){setError(cause instanceof Error?cause.message:"Unable to create your account.");setBusy(false);}}
  return <Shell title="Create your account" subtitle="Set up secure access, then create your first company."><form onSubmit={submit} className="mt-6"><label className="text-sm font-medium">Name<input required autoComplete="name" value={name} onChange={e=>setName(e.target.value)} className={inputClass}/></label><label className="mt-4 block text-sm font-medium">Email<input type="email" required autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} className={inputClass}/></label><label className="mt-4 block text-sm font-medium">Password<input type="password" minLength={8} required autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)} className={inputClass}/></label><label className="mt-4 block text-sm font-medium">Confirm Password<input type="password" minLength={8} required autoComplete="new-password" value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)} className={inputClass}/></label>{error&&<p role="alert" className="mt-4 text-sm text-rose-700">{error}</p>}<button disabled={busy} className={buttonClass}>{busy?"Creating account...":"Create account"}</button></form><p className="mt-5 text-sm text-slate-500">Already registered? <Link to="/login" className="font-medium text-blue-700">Sign in</Link></p></Shell>;
}

export function ForgotPasswordPage(){const auth=useAuth();const[email,setEmail]=useState("");const[message,setMessage]=useState<string|null>(null);const[error,setError]=useState<string|null>(null);const[busy,setBusy]=useState(false);async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError(null);try{setMessage(await auth.forgotPassword(email.trim()));}catch(cause){setError(cause instanceof Error?cause.message:"Unable to request a reset.");}finally{setBusy(false)}}return <Shell title="Reset your password" subtitle="Enter your account email to request reset instructions."><form onSubmit={submit} className="mt-6"><label className="text-sm font-medium">Email<input type="email" required value={email} onChange={e=>setEmail(e.target.value)} className={inputClass}/></label>{message&&<p role="status" className="mt-4 text-sm text-emerald-700">{message}</p>}{error&&<p role="alert" className="mt-4 text-sm text-rose-700">{error}</p>}<button disabled={busy} className={buttonClass}>Send instructions</button></form><Link to="/login" className="mt-5 inline-block text-sm text-blue-700">Back to sign in</Link></Shell>}

export function ResetPasswordPage(){const auth=useAuth();const navigate=useNavigate();const[params]=useSearchParams();const token=params.get("token")??"";const[password,setPassword]=useState("");const[error,setError]=useState<string|null>(null);const[busy,setBusy]=useState(false);async function submit(e:FormEvent){e.preventDefault();setBusy(true);try{await auth.resetPassword(token,password);navigate("/login",{replace:true});}catch(cause){setError(cause instanceof Error?cause.message:"Unable to reset the password.");setBusy(false)}}return <Shell title="Choose a new password" subtitle="Use the valid reset link sent for your account."><form onSubmit={submit} className="mt-6"><label className="text-sm font-medium">New password<input type="password" minLength={8} required value={password} onChange={e=>setPassword(e.target.value)} className={inputClass}/></label>{!token&&<p role="alert" className="mt-4 text-sm text-rose-700">This reset link has no token.</p>}{error&&<p role="alert" className="mt-4 text-sm text-rose-700">{error}</p>}<button disabled={busy||!token} className={buttonClass}>Set new password</button></form></Shell>}

