import { createContext } from "react";
import type { DashboardDto, MembershipRole } from "../api/types";
import type { Company, LedgerTransaction, NewCompany, NewParty, NewRegion, NewTransaction, Party, Region, UpdateCompany, UpdateParty, UpdateTransaction } from "../types";
import type { AppearanceSettings, AppSettingsPatch, SettingsStorageError } from "../types/settings";
import type { LedgerWorkspace } from "../types/workspace";
import type { SettingsSaveResult } from "../utils/settingsStorage";

export interface LedgerContextValue {
  companies: Company[];
  activeCompanyId: number;
  activeCompany: Company;
  companySelectionRequired: boolean;
  appearance: AppearanceSettings;
  parties: Party[];
  regions: Region[];
  transactions: LedgerTransaction[];
  storageError: SettingsStorageError | null;
  isPersisted: boolean;
  isLoading: boolean;
  error: string | null;
  activeRole: MembershipRole;
  canWrite: boolean;
  isOwner: boolean;
  dashboard: DashboardDto | null;
  refreshCompanyData: () => Promise<void>;
  createCompany: (company: NewCompany) => Promise<Company>;
  updateCompany: (companyId: number, data: UpdateCompany) => Promise<void>;
  canDeleteCompany: (companyId: number) => boolean;
  deleteCompany: (companyId: number) => Promise<void>;
  switchCompany: (companyId: number) => Promise<void>;
  addParty: (party: NewParty) => Promise<Party>;
  updateParty: (partyId: number, data: UpdateParty) => Promise<void>;
  deleteParty: (partyId: number) => Promise<void>;
  addRegion: (region: NewRegion) => Promise<Region>;
  updateRegion: (regionId: number, name: string) => Promise<void>;
  deleteRegion: (regionId: number) => Promise<void>;
  addTransaction: (transaction: NewTransaction) => Promise<LedgerTransaction>;
  updateTransaction: (transactionId: number, data: UpdateTransaction) => Promise<void>;
  deleteTransaction: (transactionId: number) => Promise<void>;
  downloadAttachment: (transactionId: number) => Promise<void>;
  deleteAttachment: (transactionId: number) => Promise<void>;
  getPartyBalance: (partyId: number) => number;
  getRegionById: (regionId: number) => Region | undefined;
  resetDemoData: () => void;
  applySettingsPatch: (patch: AppSettingsPatch) => Promise<SettingsSaveResult>;
  clearStorageError: () => void;
  getWorkspaceSnapshot: () => LedgerWorkspace;
  replaceWorkspace: (workspace: unknown) => SettingsSaveResult;
}

export const LedgerContext = createContext<LedgerContextValue | undefined>(undefined);
