import { useMemo, useState } from "react";
import { AlertTriangle, CheckCircle2, DatabaseBackup, Download, LockKeyhole, Upload } from "lucide-react";
import { toast } from "sonner";
import { backupApi } from "../../api/backupApi";
import { importApi } from "../../api/importApi";
import type { LegacyPreviewDto, RestorePreviewDto } from "../../api/types";
import { useAuth } from "../../hooks/useAuth";
import { useLedger } from "../../hooks/useLedger";
import { WORKSPACE_STORAGE_KEY } from "../../utils/workspaceStorage";

function saveBlob(blob: Blob, fileName: string) { const url=URL.createObjectURL(blob); const anchor=document.createElement("a"); anchor.href=url; anchor.download=fileName; anchor.click(); URL.revokeObjectURL(url); }
function Counts({ value }: { value: { companies:number;regions:number;parties:number;transactions:number;attachments:number } }) { return <div className="grid grid-cols-2 gap-2 sm:grid-cols-5">{Object.entries(value).map(([key,count])=><div key={key} className="rounded-xl bg-slate-50 p-3"><p className="text-lg font-semibold text-slate-950">{count}</p><p className="text-xs capitalize text-slate-500">{key}</p></div>)}</div> }

export default function Backup(){
  const { activeCompanyId, activeCompany, isOwner }=useLedger(); const auth=useAuth();
  const [backupPassphrase,setBackupPassphrase]=useState(""); const [backupConfirmation,setBackupConfirmation]=useState(""); const [restorePassphrase,setRestorePassphrase]=useState("");
  const [file,setFile]=useState<File|null>(null); const [preview,setPreview]=useState<RestorePreviewDto|null>(null); const [companyName,setCompanyName]=useState(""); const [busy,setBusy]=useState(false);
  const [legacyPreview,setLegacyPreview]=useState<LegacyPreviewDto|null>(null);
  const legacy=useMemo(()=>{try{const raw=localStorage.getItem(WORKSPACE_STORAGE_KEY);return raw?JSON.parse(raw) as unknown:null}catch{return null}},[]);
  async function createBackup(){setBusy(true);try{const result=await backupApi.create(activeCompanyId,backupPassphrase);saveBlob(result.blob,result.fileName);setBackupPassphrase("");setBackupConfirmation("");toast.success("Encrypted backup downloaded");}catch(cause){toast.error(cause instanceof Error?cause.message:"Unable to create backup.");}finally{setBusy(false)}}
  async function inspectRestore(){if(!file)return;setBusy(true);try{setPreview(await backupApi.preview(file,restorePassphrase));}catch(cause){setPreview(null);toast.error(cause instanceof Error?cause.message:"Unable to read backup.");}finally{setBusy(false)}}
  async function restore(){if(!file||!preview)return;setBusy(true);try{const result=await backupApi.commit(file,restorePassphrase,companyName||undefined);setRestorePassphrase("");setFile(null);setPreview(null);await auth.refreshBootstrap();toast.success(`${result.companyName} restored as a new company`);}catch(cause){toast.error(cause instanceof Error?cause.message:"Unable to restore backup.");}finally{setBusy(false)}}
  async function inspectLegacy(){if(!legacy)return;setBusy(true);try{setLegacyPreview(await importApi.preview(legacy));}catch(cause){toast.error(cause instanceof Error?cause.message:"Unable to inspect browser data.");}finally{setBusy(false)}}
  async function importLegacy(){if(!legacy||!legacyPreview)return;setBusy(true);try{await importApi.commit(legacy);await auth.refreshBootstrap();setLegacyPreview(null);localStorage.setItem("ledgerflow-legacy-import-completed","true");toast.success("Browser ledger imported. The original browser data was retained.");}catch(cause){toast.error(cause instanceof Error?cause.message:"Unable to import browser data.");}finally{setBusy(false)}}
  if(!isOwner)return <div className="mx-auto max-w-2xl rounded-2xl border border-amber-200 bg-amber-50 p-6"><h1 className="font-semibold text-amber-950">Owner access required</h1><p className="mt-2 text-sm text-amber-800">Encrypted backup and restore operations are restricted to company owners.</p></div>;
  return <div className="mx-auto max-w-6xl"><header><p className="text-sm font-medium text-slate-500">Data protection</p><h1 className="mt-1 flex items-center gap-3 text-3xl font-semibold text-slate-950"><DatabaseBackup size={28}/>Backup & Restore</h1><p className="mt-2 text-sm text-slate-500">Create and restore encrypted server backups for {activeCompany.name}.</p></header>
    <div className="mt-7 grid gap-6 lg:grid-cols-2"><section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><LockKeyhole className="text-blue-700"/><h2 className="mt-4 text-lg font-semibold">Create encrypted backup</h2><p className="mt-2 text-sm leading-6 text-slate-500">The backup includes company settings, ledger data, and attachment file contents. Keep the passphrase safe; it cannot be recovered.</p><label className="mt-5 block text-sm font-medium">Backup passphrase<input type="password" autoComplete="new-password" value={backupPassphrase} onChange={e=>setBackupPassphrase(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 px-3.5 py-3"/></label><label className="mt-4 block text-sm font-medium">Confirm passphrase<input type="password" autoComplete="new-password" value={backupConfirmation} onChange={e=>setBackupConfirmation(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 px-3.5 py-3"/></label><button disabled={busy||backupPassphrase.length<12||backupPassphrase!==backupConfirmation} onClick={()=>void createBackup()} className="mt-4 inline-flex items-center gap-2 rounded-xl bg-slate-950 px-5 py-3 text-sm font-semibold text-white disabled:opacity-50"><Download size={17}/>Download encrypted backup</button><p className="mt-2 text-xs text-slate-400">Use at least 12 characters.</p></section>
      <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><Upload className="text-emerald-700"/><h2 className="mt-4 text-lg font-semibold">Restore as a new company</h2><p className="mt-2 text-sm leading-6 text-slate-500">The backend decrypts and validates the file before enabling restore. Existing companies are not replaced.</p><input type="file" accept=".lfbak,application/vnd.ledgerflow.backup" onChange={e=>{setFile(e.target.files?.[0]??null);setPreview(null)}} className="mt-5 block w-full text-sm"/><input type="password" placeholder="Backup passphrase" value={restorePassphrase} onChange={e=>{setRestorePassphrase(e.target.value);setPreview(null)}} className="mt-4 w-full rounded-xl border border-slate-200 px-3.5 py-3 text-sm"/><button disabled={busy||!file||!restorePassphrase} onClick={()=>void inspectRestore()} className="mt-4 rounded-xl border border-slate-300 px-5 py-3 text-sm font-semibold disabled:opacity-50">Validate backup</button></section></div>
    {preview&&<section className="mt-6 rounded-2xl border border-emerald-200 bg-white p-6 shadow-sm"><div className="flex gap-3"><CheckCircle2 className="text-emerald-700"/><div><h2 className="font-semibold">Valid encrypted backup</h2><p className="text-sm text-slate-500">Created {preview.createdAt}. Review the counts before restoring.</p></div></div><div className="mt-5"><Counts value={preview.counts}/></div>{[...preview.warnings,...preview.conflicts].map(item=><p key={item} className="mt-2 flex gap-2 text-sm text-amber-800"><AlertTriangle size={16}/>{item}</p>)}<input value={companyName} onChange={e=>setCompanyName(e.target.value)} placeholder={`${preview.company.name} (optional new name)`} className="mt-5 w-full max-w-md rounded-xl border border-slate-200 px-3.5 py-3 text-sm"/><div><button disabled={busy||preview.conflicts.length>0} onClick={()=>void restore()} className="mt-4 rounded-xl bg-emerald-700 px-5 py-3 text-sm font-semibold text-white disabled:opacity-50">Restore as new company</button></div></section>}
    {Boolean(legacy)&&localStorage.getItem("ledgerflow-legacy-import-completed")!=="true"&&<section className="mt-6 rounded-2xl border border-blue-200 bg-blue-50 p-6"><h2 className="font-semibold text-blue-950">Legacy browser ledger detected</h2><p className="mt-2 text-sm text-blue-900">Preview and import the old LocalStorage workspace into the backend. LedgerFlow keeps the original browser data after import.</p>{!legacyPreview?<button disabled={busy} onClick={()=>void inspectLegacy()} className="mt-4 rounded-xl bg-blue-700 px-5 py-3 text-sm font-semibold text-white">Preview browser import</button>:<><div className="mt-5"><Counts value={legacyPreview.counts}/></div>{legacyPreview.warnings.map(item=><p key={`warning-${item}`} className="mt-2 flex gap-2 text-sm text-amber-800"><AlertTriangle size={16}/>{item}</p>)}{legacyPreview.conflicts.map(item=><p key={`conflict-${item}`} className="mt-2 text-sm text-rose-700">{item}</p>)}<button disabled={busy||legacyPreview.conflicts.length>0} onClick={()=>void importLegacy()} className="mt-4 rounded-xl bg-blue-700 px-5 py-3 text-sm font-semibold text-white disabled:opacity-50">Import into backend</button></>}</section>}
  </div>;
}
