param([int]$BackendPort=18087,[int]$FrontendPort=15173)
$ErrorActionPreference="Stop"
$root=Split-Path -Parent $PSScriptRoot;$backend=Join-Path $root "backend";$frontend=Join-Path $root "frontend";$target=Join-Path $backend "target";$run=Join-Path $target ("m7-smoke-"+[guid]::NewGuid().ToString("N"));[IO.Directory]::CreateDirectory($run)|Out-Null
$java=Join-Path $env:JAVA_HOME "bin\java.exe";$jar=Join-Path $target "ledgerflow-backend-0.0.1-SNAPSHOT.jar";$base="http://127.0.0.1:$BackendPort";$front="http://127.0.0.1:$FrontendPort";$cookies=Join-Path $run "cookies.txt";$response=Join-Path $run "response.json";$request=Join-Path $run "request.json";$backup=Join-Path $run "company.lfbak";$pdf=Join-Path $run "invoice.pdf";$download=Join-Path $run "download.pdf";$legacy=Join-Path $run "legacy-localstorage.json";$server=$null;$web=$null
function Utf8($path,$value){[IO.File]::WriteAllText($path,$value,[Text.UTF8Encoding]::new($false))}
function Invoke-Curl([string[]]$Arguments){& curl.exe @Arguments;if($LASTEXITCODE-ne 0){throw "curl failed ($LASTEXITCODE)"}}
function Csrf{Invoke-Curl @("--fail","-sS","-c",$cookies,"-b",$cookies,"$base/api/auth/csrf","-o",$response);$line=Get-Content $cookies|Where-Object{$_-match "XSRF-TOKEN"}|Select-Object -Last 1;if(!$line){throw "No CSRF cookie"};return (($line-split "`t")[-1])}
function Mutate($method,$path,$body){$token=Csrf;Utf8 $request $body;Invoke-Curl @("--fail-with-body","-sS","-X",$method,"-c",$cookies,"-b",$cookies,"-H","Content-Type: application/json","-H","X-XSRF-TOKEN: $token","--data-binary","@$request","$base$path","-o",$response);return(Get-Content $response -Raw|ConvertFrom-Json)}
function GetApi($path){Invoke-Curl @("--fail-with-body","-sS","-b",$cookies,"$base$path","-o",$response);return(Get-Content $response -Raw|ConvertFrom-Json)}
try{
  if(!(Test-Path $java)){throw "JAVA_HOME must point to JDK 23"};if(!(Test-Path $jar)){throw "Package the backend first"}
  $server=Start-Process $java -ArgumentList @("-Dserver.port=$BackendPort","-Dledgerflow.database.path=$(Join-Path $run 'ledgerflow.db')","-Dledgerflow.data-dir=$(Join-Path $run 'data')","-Dledgerflow.backups.pbkdf2-iterations=100000","-Dlogging.level.root=WARN","-jar",$jar) -WorkingDirectory $backend -WindowStyle Hidden -PassThru -RedirectStandardOutput (Join-Path $run "backend.out.log") -RedirectStandardError (Join-Path $run "backend.err.log")
  $env:VITE_API_BASE_URL=$base;$web=Start-Process (Get-Command npm.cmd).Source -ArgumentList @("run","dev","--","--host","127.0.0.1","--port",$FrontendPort) -WorkingDirectory $frontend -WindowStyle Hidden -PassThru -RedirectStandardOutput (Join-Path $run "frontend.out.log") -RedirectStandardError (Join-Path $run "frontend.err.log")
  $ready=$false;$readinessError="";for($i=0;$i-lt 120;$i++){try{Invoke-Curl @("--fail","-sS","--connect-timeout","1","$base/api/auth/csrf","-o",$response);Invoke-Curl @("--fail","-sS","--connect-timeout","1","$front/login","-o",(Join-Path $run "frontend.html"));$ready=$true;break}catch{$readinessError=$_.Exception.Message;Start-Sleep -Milliseconds 250}};if(!$ready){throw "Applications did not become ready: $readinessError"};if(!((Get-Content (Join-Path $run "frontend.html") -Raw)-match "LedgerFlow")){throw "Frontend did not serve LedgerFlow"}
  Mutate POST "/api/auth/register" '{"name":"M7 Smoke Owner","email":"smoke-m7@example.com","password":"correct horse battery staple"}'|Out-Null;Mutate POST "/api/auth/login" '{"email":"smoke-m7@example.com","password":"correct horse battery staple"}'|Out-Null
  if((GetApi "/api/me/bootstrap").data.companies.Count-ne 0){throw "New account did not start with zero companies"}
  $company=(Mutate POST "/api/companies" '{"name":"M7 Smoke Company","address":"Integration Road","phone":"9876543210"}').data.id;$region=(Mutate POST "/api/companies/$company/regions" '{"name":"Punjab"}').data.id;$party=(Mutate POST "/api/companies/$company/parties" "{`"regionId`":$region,`"name`":`"Smoke Party`",`"phone`":`"9876543210`"}").data.id
  $credit=(Mutate POST "/api/companies/$company/transactions" "{`"partyId`":$party,`"type`":`"CREDIT`",`"amount`":25000,`"transactionDate`":`"2026-09-14`",`"description`":`"Invoice`"}").data.id;$debit=(Mutate POST "/api/companies/$company/transactions" "{`"partyId`":$party,`"type`":`"DEBIT`",`"amount`":10000,`"transactionDate`":`"2026-09-14`",`"description`":`"Payment`"}").data.id
  $dashboard=(GetApi "/api/companies/$company/dashboard").data;if($dashboard.netBalance-ne 15000-or $dashboard.totalReceivable-ne 15000){throw "Dashboard balance mismatch"};if((GetApi "/api/companies/$company/parties/$party").data.balance-ne 15000){throw "Party balance mismatch"}
  Mutate PATCH "/api/companies/$company/transactions/$debit" '{"description":"Payment edited","transactionDate":"2026-09-14"}'|Out-Null;$statement=(GetApi "/api/companies/$company/reports/party-statement?partyId=$party").data;if($statement.closingBalance-ne 15000-or $statement.displayedTransactionCount-ne 2){throw "Statement mismatch"};if((GetApi "/api/companies/$company/reports/date-range?from=2026-09-14&to=2026-09-14").data.netMovement-ne 15000){throw "Date report mismatch"}
  Utf8 $pdf "%PDF-1.4`nLedgerFlow M7 smoke";$token=Csrf;Invoke-Curl @("--fail","-sS","-X","POST","-c",$cookies,"-b",$cookies,"-H","X-XSRF-TOKEN: $token","-F","file=@$pdf;type=application/pdf","$base/api/companies/$company/transactions/$credit/attachment","-o",$response);Invoke-Curl @("--fail","-sS","-b",$cookies,"$base/api/companies/$company/transactions/$credit/attachment","-o",$download);if(![Linq.Enumerable]::SequenceEqual([byte[]][IO.File]::ReadAllBytes($pdf),[byte[]][IO.File]::ReadAllBytes($download))){throw "Attachment mismatch"}
  $pass="M7 smoke backup passphrase";$token=Csrf;Utf8 $request "{`"passphrase`":`"$pass`"}";Invoke-Curl @("--fail","-sS","-X","POST","-c",$cookies,"-b",$cookies,"-H","Content-Type: application/json","-H","X-XSRF-TOKEN: $token","--data-binary","@$request","$base/api/companies/$company/backup","-o",$backup);$token=Csrf;Invoke-Curl @("--fail","-sS","-X","POST","-c",$cookies,"-b",$cookies,"-H","X-XSRF-TOKEN: $token","-F","file=@$backup;type=application/vnd.ledgerflow.backup","-F","passphrase=$pass","$base/api/backups/restore/preview","-o",$response);$preview=Get-Content $response -Raw|ConvertFrom-Json;if($preview.data.counts.transactions-ne 2-or $preview.data.counts.attachments-ne 1){throw "Backup preview mismatch"}
  $token=Csrf;Invoke-Curl @("--fail","-sS","-X","POST","-c",$cookies,"-b",$cookies,"-H","X-XSRF-TOKEN: $token","-F","file=@$backup;type=application/vnd.ledgerflow.backup","-F","passphrase=$pass","-F","companyName=M7 Smoke Restored","$base/api/backups/restore/commit","-o",$response);$restored=(Get-Content $response -Raw|ConvertFrom-Json).data.companyId;if((GetApi "/api/companies/$restored/dashboard").data.netBalance-ne 15000){throw "Restored data mismatch"}
  Mutate PATCH "/api/me/preferences" "{`"rememberLastCompany`":true,`"lastActiveCompanyId`":$restored}"|Out-Null;Mutate POST "/api/auth/logout" '{}'|Out-Null;Mutate POST "/api/auth/login" '{"email":"smoke-m7@example.com","password":"correct horse battery staple"}'|Out-Null;$boot=(GetApi "/api/me/bootstrap").data;if($boot.companies.Count-ne 2-or $boot.preferences.lastActiveCompanyId-ne $restored){throw "Re-login bootstrap mismatch"}
  $legacyJson='{"format":"ledgerflow-backup","version":1,"scope":"full","createdAt":"2026-09-14T10:00:00Z","data":{"companies":[{"id":900,"name":"Legacy Browser Co","address":"","phone":"","gstin":"","email":"","createdAt":"2026-01-01T00:00:00Z","settings":{"statementHeader":"Statement of Account","statementFooter":"","print":{"defaultTransactionLimit":25,"showRunningBalance":true,"showNotes":false,"showAttachment":true,"showBusinessAddress":true,"showBusinessPhone":true,"showBusinessGstin":true,"showGeneratedDate":true,"showPageNumbers":true,"paperSize":"A4","orientation":"portrait","fontSize":"normal","customFooter":""}}}],"activeCompanyId":900,"regions":[{"id":901,"companyId":900,"name":"North"}],"parties":[{"id":902,"companyId":900,"name":"Legacy Party","phone":"","regionId":901,"address":"","gstin":"","notes":"","createdAt":"2026-01-01T00:00:00Z"}],"transactions":[{"id":903,"companyId":900,"partyId":902,"type":"CREDIT","amount":5000,"transactionDate":"2026-09-14","description":"Legacy invoice","notes":"","createdAt":"2026-09-14T10:00:00Z"}],"applicationSettings":{"appearance":{"fontFamily":"inter","baseFontSize":16,"uiScale":100,"density":"comfortable","tableDensity":"normal","accentColor":"blue","theme":"light"}}}}';Utf8 $legacy $legacyJson;$legacyPreview=(Mutate POST "/api/import/legacy/preview" $legacyJson).data;if($legacyPreview.counts.transactions-ne 1){throw "Legacy preview mismatch"};$legacyId=(Mutate POST "/api/import/legacy/commit" $legacyJson).data.companyIds[0];if((GetApi "/api/companies/$legacyId/parties").data[0].balance-ne 5000){throw "Legacy balance mismatch"};if(!(Test-Path $legacy)){throw "Legacy source was removed"}
  Write-Output "FRONTEND_BACKEND_SMOKE_OK";Write-Output "LEGACY_IMPORT_UI_SMOKE_OK"
}finally{if($web-and!$web.HasExited){Stop-Process $web.Id -Force};$listener=Get-NetTCPConnection -LocalPort $FrontendPort -State Listen -ErrorAction SilentlyContinue;if($listener){$listener|ForEach-Object{Stop-Process $_.OwningProcess -Force -ErrorAction SilentlyContinue}};if($server-and!$server.HasExited){Stop-Process $server.Id -Force}}

